### PR TITLE
Two step sandbox overlay

### PR DESCRIPTION
**Pull request by StevenDufresne**
Building on #1, this PR takes the browser-like experience we currently have in the wordpress-wasm project and adds it to the theme. It also allows users to overlay the settings so there isn't a context shift when wanting to change properties.

I ran out of time on this, but wanted to get up a draft PR to discuss this approach. The browser and background styles from the original project have only been mimicked for example sake. I have also started sourcing some of the `wporg` styles that are coming together in the design library for the modal window (which is incomplete).

Check demo:
https://d.pr/i/diTjtJ

@adamziel

### CODE REVIEW

**Comment by StevenDufresne** [comment]
I made some updates by bringing some of the browser styles over. I can't get the iframe running though. 

@adamziel 
I keep running into:
Screen Shot 2022-11-28 at 3 31 05 PM

**Comment by adamziel** [comment]
@StevenDufresne I also noticed this lately, it happens when a plugin fails to install – the error message could be much better. I'm looking into that.

**Comment by adamziel** [comment]
@StevenDufresne fixed in https://github.com/WordPress/wordpress-wasm/commit/743f8fa98b25d512070dbee8b869e1c0aa50eaa3

Turns out I changed `response.body` to be an ArrayBuffer instead of a string, but forgot to adjust the code that consumed it. I didn't realize when project reached a scale where a higher test coverage becomes indispensable!

**Comment by adamziel** [comment]
@StevenDufresne I've pulled from your branch, added a few commits, and started https://github.com/StevenDufresne/wordpress-wasm/pull/3:


CleanShot 2022-11-28 at 23 16 11@2x

**Pull request merged**
